name: "Update Poster"
on: [push, workflow_dispatch]
jobs:
  update-poster:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.update.outputs.updated }}
    steps:
      - name: checkout main branch
        uses: actions/checkout@v3

      - name: Download Files.
        run: bash downloader.sh downloadlist.csv

      - name: Upload GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site/

  deploy:
    needs: update-poster
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
