name: "Update Poster"
on: [workflow_dispatch]
jobs:
  update-poster:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.update.outputs.updated }}
    steps:
      - name: checkout main branch
        uses: actions/checkout@v3
      - name: Set Download ID Env.
        run: echo "GoogleDriveID=$(cat GoogleDriveID.txt | head -n 1)" >> $GITHUB_ENV

      - name: update Poster
        id: update
        run: wget "https://drive.google.com/uc?export=download&id=${{ env.GoogleDriveID }}" -O ${{ env.GITHUB_OUTPUT }}/AlphaPoster-v1.png


      - name: Upload GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site/

  deploy:
    needs: update-poster
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
